# Evaluación Diagnóstico 
### Felipe Martínez Nakousi
### IIC2154 - Sección 3

#### Importar librerías

In [2]:
import pandas as pd
from pandas.io.json import json_normalize
import warnings
import json
warnings.filterwarnings("ignore")

##### Definir Dataset

In [3]:
with open('dataset.json') as file:
     data = [json.loads(line) for line in file.readlines()]

In [15]:
df = pd.json_normalize(data)
df.head()

,url,date,content,renderedContent,id,outlinks,tcooutlinks,replyCount,retweetCount,likeCount,...,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quoteCount,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.conversationId,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.lang,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.source,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.sourceUrl,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.sourceLabel,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.media,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.retweetedTweet,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet,quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.quotedTweet.mentionedUsers
0,https://twitter.com/ShashiRajbhar6/status/1376...,2021-03-30T03:33:46+00:00,Support 👇\n\n#FarmersProtest,Support 👇\n\n#FarmersProtest,1376739399593910273,[],[],0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://twitter.com/kaursuk06272818/status/137...,2021-03-30T03:33:23+00:00,Supporting farmers means supporting our countr...,Supporting farmers means supporting our countr...,1376739306287427584,[],[],0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://twitter.com/kaursuk06272818/status/137...,2021-03-30T03:31:00+00:00,Support farmers if you are related to food #St...,Support farmers if you are related to food #St...,1376738704128020488,[],[],0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://twitter.com/SukhdevSingh_/status/13767...,2021-03-30T03:30:45+00:00,#StopHateAgainstFarmers support #FarmersProtes...,#StopHateAgainstFarmers support #FarmersProtes...,1376738640542400518,[],[],0,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://twitter.com/Davidmu66668113/status/137...,2021-03-30T03:30:30+00:00,"You hate farmers I hate you, \nif you love the...","You hate farmers I hate you, \nif you love the...",1376738579171344386,[],[],0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### Funciones

In [61]:
def most_retweeted(df,n=10):
    # Recibe dataframe y retorna los 10 tweets mas retweeteados.
    top10 = df.nlargest(n, columns=['retweetCount'])
    return top10[['content', 'retweetCount', 'user.username']]
    

testdf = df.sample(n=1000, random_state=1)
most_retweeted(testdf)

,content,retweetCount,user.username
346984,The whole bollywood woke up suddenly to call o...,1711,RoopBhinderr
310750,Speaking out against Global Human Rights viola...,1046,Fridays4future
197889,Which organisations or individuals are providi...,932,RaviSinghKA
197398,सीधा कॉल to टॉप सेलेब्रिटीज़\nSalute to Abhina...,500,speakupssc1
104117,God bless our Farmers🤲 \nI pray our Farmers re...,241,meeetgill
194649,The 74-year-old actor shared a news report by ...,238,thewire_in
92563,Farmers work hard to make sure we have food on...,196,NavJammu
375546,I thanks to @LicypriyaK for motivate world to...,173,AapSriniwas
298268,Absolutely Right @taapsee \n\n#FarmersProtest\...,141,sandeepsurya_
405978,Siropa for #Rihanna and lakh lanata for Bollyw...,89,HeerSaleti_

In [44]:
def most_tweets(df,n=10):
    # Recibe dataframe y retorna los 10 usuarios con más tweets.
    return df['user.username'].value_counts()[:n]

most_tweets(testdf)

harjot_tweeting    17
rebelpacifist      10
rumsomal            7
NavJammu            5
pawanrai1313        5
shells_n_petals     5
diljit_maan12       4
Iamjazzie96         4
BinduGhuman         4
1Kuldeep2           4
Name: user.username, dtype: int64

In [62]:
def dias_con_mas_tweets(df,n=10):
    # Recibe dataframe y retorna dias con más tweets.
    df['dia']=df['date'].str[:9]
    return df['dia'].value_counts()[:n]
    
dias_con_mas_tweets(testdf)

2021-02-0    620
2021-02-1    113
2021-02-2     80
2021-03-0     64
2021-03-2     63
2021-03-1     59
2021-03-3      1
Name: dia, dtype: int64

In [64]:
def hashtags_mas_usados(df, n=10):
    return df.content.str.extractall(r'(\#\w+)')[0].value_counts()[:n]

hashtags_mas_usados(testdf)

#FarmersProtest              964
#farmersprotest               37
#IStandWithFarmers            34
#Rihanna                      32
#FarmersAreIndia              31
#StandWithFarmers             27
#IndianFarmersHumanRights     26
#HumanRights                  19
#ReleaseDetainedFarmers       17
#FreeNodeepKaur               16
Name: 0, dtype: int64